apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sqlsvc.name }}
spec:
  ports:
  - port: {{ .Values.sqlsvc.port }}
    protocol: TCP
  selector:
    app: {{ .Values.sqlsvc.name }}
  type: {{ .Values.sqlsvc.type }}
